luku1 = int(input(("Ensimmäinen luku: ")))
luku2 = int(input(("Toinen luku: ")))
luku3 = int(input(("Kolmas luku: ")))
summa = luku1 + luku2 + luku3
tulo = luku1 * luku2 * luku3
keskiarvo = summa/3
print(f"Summa = {summa}")
print(f"Tulo = {tulo}")
print(f"Keskiarvo = {keskiarvo}")